### ISSUE TITLE
Implement source language as (De Bruijn style) lambda calculus and port AD transforms to that

### ISSUE THREAD

**Issue by VMatthijs** [VMatthijs/CHAD#3]
(Ideally with sharing between primal and (co)tangent passes.)

I see that @tomsmeding  is already making progress on this in a branch. :-)

**Comment by tomsmeding** [comment]
This is now done and working on the `main` branch :)

**Comment by tomsmeding** [comment]
Note that a couple of things from the previous combinator version are yet unimplemented in the new lambda-calculus version:

- Some array combinators like `foldr`
- Iteration `It` and recursion `Rec`
- Coproducts (sum types)
